"""empty message

Revision ID: 02a1c5275dd3
Revises: 874e6e691efd
Create Date: 2020-08-07 12:05:35.837112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02a1c5275dd3'
down_revision = '874e6e691efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('chapter_html_after', sa.String(length=50), nullable=True))
    op.add_column('chapter', sa.Column('chapter_html_before', sa.String(length=50), nullable=True))
    op.add_column('chapter', sa.Column('chapter_name_after', sa.String(length=50), nullable=True))
    op.add_column('chapter', sa.Column('chapter_name_before', sa.String(length=50), nullable=True))
    op.drop_column('chapter', 'name_after')
    op.drop_column('chapter', 'chaper_html_after')
    op.drop_column('chapter', 'name_before')
    op.drop_column('chapter', 'chaper_html_before')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('chaper_html_before', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('chapter', sa.Column('name_before', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('chapter', sa.Column('chaper_html_after', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('chapter', sa.Column('name_after', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('chapter', 'chapter_name_before')
    op.drop_column('chapter', 'chapter_name_after')
    op.drop_column('chapter', 'chapter_html_before')
    op.drop_column('chapter', 'chapter_html_after')
    # ### end Alembic commands ###
