"""empty message

Revision ID: 3ed04d7cf38a
Revises: c810add71425
Create Date: 2020-08-06 13:12:53.531706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed04d7cf38a'
down_revision = 'c810add71425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_html_html'), 'html', ['html'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_html_html'), table_name='html')
    # ### end Alembic commands ###
