"""empty message

Revision ID: 874e6e691efd
Revises: 3ed04d7cf38a
Create Date: 2020-08-06 20:27:14.013338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874e6e691efd'
down_revision = '3ed04d7cf38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_html_html', table_name='html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_html_html', 'html', ['html'], unique=True)
    # ### end Alembic commands ###
