"""1

Revision ID: c810add71425
Revises: 
Create Date: 2020-08-04 12:01:52.236121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c810add71425'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_before', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_before', sa.String(length=50), nullable=True),
    sa.Column('name_after', sa.String(length=50), nullable=True),
    sa.Column('chaper_html_before', sa.String(length=50), nullable=True),
    sa.Column('chaper_html_after', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('html',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('html')
    op.drop_table('chapter')
    op.drop_table('book')
    # ### end Alembic commands ###
