"""empty message

Revision ID: fbe951f7440d
Revises: c915ccf44561
Create Date: 2020-08-08 13:48:54.405894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe951f7440d'
down_revision = 'c915ccf44561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('chapter_content', sa.String(length=50), nullable=True))
    op.add_column('html', sa.Column('book_name', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('html', 'book_name')
    op.drop_column('chapter', 'chapter_content')
    # ### end Alembic commands ###
